name: Auto-Sync Branches with Main

on:
  push:
    branches:
      - main

jobs:
  sync-branches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Merge main into feature branches
        run: |
          branches=("feat/www" "feat/ai-chat" "feat/analytic-engine" "feat/messages" "feat/appointments" "feat/backend-auth" "feat/webui" "dev")
          for branch in "${branches[@]}"; do
            git fetch origin $branch
            git checkout $branch
            git merge origin/main --no-edit || echo "Merge conflict in $branch, needs manual resolution"
            git push origin $branch
          done
